### ISSUE TITLE
Https/ssl

### ISSUE THREAD

**Issue by rodrigocoutlopes** [HashLoad/horse#110]
O Horse está funcionando com HTTPs?

**Comment by viniciussanchez** [comment]
A versão 2.0 do Horse esse recurso vai ser nativo. 
Na versão atual, voce precisa configurar o HTTPS no seu servidor de aplicação, por exemplo no IIS ou nginx

**Comment by rodrigocoutlopes** [comment]
Então eu conseguiria fazer isso rodando no apache? certo?
Alguma previsão da versão 2.0?
Obrigado pela informação. Grande abraço

**Comment by viniciussanchez** [comment]
> Então eu conseguiria fazer isso rodando no apache? certo?

Sim

> Alguma previsão da versão 2.0?

01/09/2020 as 20h acontecerá uma live da versão 2.0

**Comment by rafaelevoinfo** [comment]
Na versão 2.0.14 o recurso para suporte a https já existe?

**Comment by viniciussanchez** [comment]
Sim
