### ISSUE TITLE
Stop Service

### ISSUE THREAD

**Issue by marcianobandeira** [HashLoad/horse#111]
Boa tarde,

É possível startar o horse sem bloquear o fluxo da aplicação? pensei em talvez colocar em uma thread a parte, mas não vi opção de fazer um stop.

O leque de possibilidades que o horse abre é muito grande, um cenario que tenho aqui é para anexar comprovantes de pagamento em titulos financeiros, no sistema desktop.
Este anexo pode ser um arquivo pdf ou uma foto. No caso da foto, pensei em fazer um app no celular para tirar a foto e enviar para o sistema.
Seria simples fazer um serviço e deixar rodando no servidor para isso, mas como são muitas empresas utilizando, inviabiliza a instalação de um serviço em casa empresa, pensei em startar a instancia do horse em um formulario exibindo um qrcode com a url do servico, para que o aplicativo faça a foto e envie ao sistema. Após concluir esse processo poderia dar um stop no horse.

Seria possível trabalhar desta forma?

Grato

**Comment by viniciussanchez** [comment]
Boa tarde...
Na versão 2.0 vai ter a opção de stop do servidor (console), já em projetos como ISAPI quem da o stop é no IIS. Mesma coisa com projetos rodando no apache.

**Comment by marcianobandeira** [comment]
opa legal, vou aguardar a nova versão então, parabéns pelo trabalho.
