### ISSUE TITLE
Apache não está rodando

### ISSUE THREAD

**Issue by rodrigocoutlopes** [HashLoad/horse#112]
Estou testando o mod_apache e ele não está rodando.

Está apresentando o erro em anexo.

![Screenshot_1](https://user-images.githubusercontent.com/69587274/90053600-1c47a180-dcb1-11ea-983f-a7727c2935f9.png)

**Comment by rodrigocoutlopes** [comment]
ao compilar o pacote

![Screenshot_2](https://user-images.githubusercontent.com/69587274/90055706-2919c480-dcb4-11ea-8cc8-a27024c6d299.png)

![Screenshot_3](https://user-images.githubusercontent.com/69587274/90055720-2d45e200-dcb4-11ea-99c1-6006847c6ca2.png)

**Comment by CarlosHe** [comment]
Olá, boa tarde! Vamos verificar essa questão do Horse (da branch master) no Apache! Consegue anexar o seu exemplo aqui?

**Comment by rodrigocoutlopes** [comment]
Peguei o projeto na pasta sample...o teste do ping

![Screenshot_4](https://user-images.githubusercontent.com/69587274/90056684-a4c84100-dcb5-11ea-9a6e-1d1f324ee966.png)

**Comment by CarlosHe** [comment]
Olá, então, realizamos um ajuste na versão atual da branch master para corrigir essa exception que ocorria quando usava o Apache! A versão da branch unicorn (versão futura do Horse) já tinha a correção para o correto funcionamento!

**Comment by rodrigocoutlopes** [comment]
![Screenshot_5](https://user-images.githubusercontent.com/69587274/90085114-8aaa5500-dced-11ea-9a86-89ab7380ce83.png)

**Comment by CarlosHe** [comment]
Agora basta chamar uma rota que você cadastrou!
