### ISSUE TITLE
Problema com Body<T> e algumas sugestões.

### ISSUE THREAD

**Issue by marcianobandeira** [HashLoad/horse#114]
Boa tarde,

Desculpe incomodar, mas estou fazendo varios testes com o horse e estou achando muito top.

Tive um probleminha com a função Body<T> usando generics, neste caso não retornou meu objeto corretamente.. tive que fazer desta forma, 

login := TJson.JsonToObject<TLoginDto>(req.Body);

pode ser que eu esteja interpretando errado a rotina Body<T>.

Outra coisa que notei, quando quero enviar um status code se nao enviar um corpo no resultado, o postman recebe um exception e nao o status code retornado... por exemplo:

// assim da erro
resp.Status(THTTPStatus.BadRequest.ToInteger);

// assim funciona
resp.Send('não enviado dados para login').Status(THTTPStatus.BadRequest.ToInteger);

Notei também que é necessário gerar um EHorseCallbackInterrupted para que o processamento não continue, aqui seria apenas uma sugestão... 

// trecho de codigo atual
    if login = nil then
      begin
        resp.Send('não enviado dados para login').Status(THTTPStatus.BadRequest.ToInteger);
        raise EHorseCallbackInterrupted.Create;
      end
    else if (login.login <> 'marciano') or (login.senha <> '123') then
      begin
        resp.Send('Unauthorized').Status(THTTPStatus.Unauthorized.ToInteger);
        raise EHorseCallbackInterrupted.Create;
      end;

// trecho otimizado (necessario implementacoes no horse)
    if login = nil then
      // resp.raiseBadRequest('com mensagem');
      resp.raiseBadRequest(); // sem mensagem
    else if (login.login <> 'marciano') or (login.senha <> '123') then
      resp.raiseUnauthorized();

Desculpe se ja tem coisas que já estão na nova versão.
Também fico a disposição para implementar as sugestões.

**Comment by CarlosHe** [comment]
Pra retornar o Json no body da request, tem que utilizar o middleware do json ( https://github.com/HashLoad/jhonson )
Esse middleware converte o tipo do objeto TJsonValue para json string

**Comment by CarlosHe** [comment]
E em relação ao retorno do erro disparado com uma raise exception, utilize o EHorseException

**Comment by CarlosHe** [comment]
EHorseException tem o Status (o código do erro) e Error (a mensagem do erro)

**Comment by marcianobandeira** [comment]
Tentei EHorseException passando status code e corpo, mas neste caso o postman não foi capaz de pegar o resultado correto.
Quanto ao jhonson esqueci de mencionar mas já estou usando ele, ocorre que na implementação do método pelo que vi há apenas uma tentativa de conversão do body json, algo como T(LBody)... mas dessa forma não obtive o meu objeto preenchido com os dados do json.

**Comment by CarlosHe** [comment]
Consegue anexar um exemplo mínimo aqui?

**Comment by marcianobandeira** [comment]
Opa consigo sim, provavelmente bem mais tarde, mas assim que der já subo

**Comment by marcianobandeira** [comment]
Segue exemplo

unit Models;

interface

uses
  Rest.Json.Types;

type
  TLoginDto = class
    [JsonName('login')]
    login: String;

    [JsonName('senha')]
    senha: String;
  end;

implementation

end.

program ExemploHorse;

{$APPTYPE CONSOLE}

{$R *.res}

uses
  System.SysUtils,
  Rest.Json.Types,
  Horse,
  Horse.Jhonson,
  Rest.Json,
  System.Json,
  Models in 'Models.pas';

var app: THorse;
begin
  try
    app := THorse.Create(9000);
    app.Use(Jhonson);

    app.Post('/conta/login',
      procedure(req: THorseRequest; resp: THorseResponse; next: TProc)
      var dto : TLoginDto;
          dto2: TLoginDto;
      begin
        // funciona
        try
          dto2 := TJson.JsonToObject<TLoginDto>(req.Body);
          try
            WriteLn(dto2.login);
          finally
            FreeAndNil(dto2);
          end;
        except
          on e: Exception do
            WriteLn(e.Message);
        end;

        // nao funciona
        try
          dto := req.Body<TLoginDto>();
          try
            WriteLn(dto.login);
          finally
            FreeAndNil(dto);
          end;
        except
          on e: Exception do
            WriteLn(e.Message);
        end;
      end
    );

    app.Start;
  except
    on E: Exception do
      Writeln(E.ClassName, ': ', E.Message);
  end;
end.

**Comment by marcianobandeira** [comment]
este é o json da requisicao feita pelo postman

{"login":"marciano","senha":"123"}

**Comment by CarlosHe** [comment]
Então, observei alguns detalhe em relação ao seu código!

Vou copiar aqui o trecho do código na qual você diz não funcionar!

```delphi
...
try
  dto := req.Body<TLoginDto>();
  try
    WriteLn(dto.login);
  finally
    FreeAndNil(dto);
  end;
except
  on e: Exception do
    WriteLn(e.Message);
end;
...
```

TLoginDto é uma classe que você criou, para trabalhar com models! No caso, o Jhonson não converte a request json para uma classe que não seja do tipo TJsonValue! Não é realizada uma conversão do json para um objeto que você criou! O Jhonson apenas converte a string recebida para um TJsonValue!

Outro detalhe, tudo que é recebido e enviado no content do Horse (response content and request content), não precisa ser destruído! O Horse já é responsável por destruir os objetos do content!

Vou dar uma segestão de como pode ficar o seu código utilizando o Jhonson:

```delphi
...
var
  LJsonObject: TJsonObject;
  LLoginDto: TLoginDto;
begin
  LJsonObject := Req.Body<TJsonObject>;
  LLoginDto := TJson.JsonToObject<TLoginDto>(LJsonObject);
  try
    WriteLn(LLoginDto.Login);
  finally
    FreeAndNil(LLoginDto);
  end;
end;
...
```

**Comment by marcianobandeira** [comment]
Entendo, na prática acabou ficando como já estou fazendo mesmo, mas há de se levar em conta que ter um Body<T> usando generics deixa pouco intuitivo ao desenvolvedor, já que genérics serve justamente pra trabalhar com classes próprias, talvez fosse melhor ter um BodyJson pra deixar claro que é apenas pra objetos json, mas é somente minha humilde opinião.

**Comment by CarlosHe** [comment]
Mas hoje o body não é apenas para json, dependendo do seu endpoint, você pode receber arquivos ou enviar arquvos, tem middlewares para envio de stream! Você também pode desenvolver um middleware que já converta diretamente para um objeto seu! Aí você pode usar do modo que estava tentando fazer!

**Comment by marcianobandeira** [comment]
Me referia apenas ao overload Body<T>... mas tranquilo, nada que um ClassHelper não resolva tudo isso. Obrigado amigo, boa noite
