### ISSUE TITLE
Incompabilitade entre os middlewares Compression e Paginate

### ISSUE THREAD

**Issue by giulianon** [HashLoad/horse#115]
Ao usar o middleware **Paginate** juntamente com o **Compression** acontecem problemas.

Conforme a ordem do registro o problema muda.

Se usar nessa ordem não acontece erro mas a paginação não funciona.
App.Use(Compression());
App.Use(Paginate);

Se inverter a ordem o send não é enviado e gera um erro no client.
App.Use(Paginate);
App.Use(Compression());

**Comment by viniciussanchez** [comment]
Poderia printar aqui os erros em ambas as situações?

**Comment by giulianon** [comment]
Então Vinicius...no exemplo do paginate mesmo já dá pra simular os dois problemas.
https://github.com/bittencourtthulio/Horse-Paginate/tree/master/sample

Basta incluir nele o registro do Compression antes ou depois do registro do Paginate e incluir as informações no header que o paginate exige.

Seguem os prints.

![CompressionAntesDoPaginate](https://user-images.githubusercontent.com/4398443/90130757-60828280-dd41-11ea-8db5-984f0f25fc3d.png)
![CompressionaDepoisDoPaginate](https://user-images.githubusercontent.com/4398443/90130771-64aea000-dd41-11ea-94d1-088c9cf54abd.png)

**Comment by viniciussanchez** [comment]
Olha so o middleware paginate

![image](https://user-images.githubusercontent.com/16382981/90132352-06cf8780-dd44-11ea-8b63-b6d0c4c76c3c.png)

Agora olha o middleware compression

![image](https://user-images.githubusercontent.com/16382981/90132427-37172600-dd44-11ea-9308-f2e69f84da27.png)

**Comment by CarlosHe** [comment]
#Resolved: https://github.com/bittencourtthulio/Horse-Paginate/pull/4
