### ISSUE TITLE
Bootstrap Sample

### ISSUE THREAD

**Issue by 1Dragon** [HashLoad/horse#129]
hello Vinicius,

is possible to you, add a small sample in bootstrap to create a datatable or table from dataset in horse?
also put values on variables in html page, imagine i have a **total sales** variable, in server, i calculate the value and change the variable value on the html?

would be very grateful for the help.

**Comment by viniciussanchez** [comment]
Hello,
Here is an Angular example consuming a Horse API
https://github.com/viniciussanchez/embarcadero-conference/tree/master/2020
It's not part of the Horse idea, so we are not going to add the samples folder.
