### ISSUE TITLE
Router Regex (URL-Parameters)

### ISSUE THREAD

**Issue by thevinge** [HashLoad/horse#130]
Hi,

Is it possible to define a route using regular expressions?
Is it possible to define an endpoint containing URL-parameters?

For instance:
When I have registered the following endpoint: Localhost:9000/api/locate/
and I send a request to Localhost:9000/api/locate/?name=Apple 
"not found" is returned.

See ExpressJs for inspiration:
https://expressjs.com/en/guide/routing.html

**Comment by viniciussanchez** [comment]
> Is it possible to define an endpoint containing URL-parameters?

Yes, it's possible

> Is it possible to define a route using regular expressions?

Not at the moment

**Comment by thevinge** [comment]
> > Is it possible to define an endpoint containing URL-parameters?
> 
> 
> 
> Yes, it's possible
> 
> 
> 
> > Is it possible to define a route using regular expressions?
> 
> 
> 
> Not at the moment
> 
> 

Great - I have since tested it and it works. 

Are you planning on implementing regex routing in the future?

**Comment by viniciussanchez** [comment]
We can think for version 3.0
