### ISSUE TITLE
A misspelling in your readme.md

### ISSUE THREAD

**Issue by rafael-figueiredo-alves** [HashLoad/horse#133]
Sorry to disturb, but I've noticed a misspelling (an) in your readme.md in the following line:

``For an more maintainable ``

The correct (a) is:

``For a more maintainable``

By the way, if you want any help with the documentation or something (code), I'd be happy.

**Comment by viniciussanchez** [comment]
Excuse me,
Feel free to make the change and send the PR.

**Comment by viniciussanchez** [comment]
I just made adjustments
