### ISSUE TITLE
Listen on Multiple Ports

### ISSUE THREAD

**Issue by thevinge** [HashLoad/horse#136]
Hi,

Is it possible to listen on multiple ports using Horse?

Maybe it can be achieved by just creating multiple Horse Instances?

**Comment by viniciussanchez** [comment]
It's not possible to have multiple instances of THorse in a single project. To have multiple instances, it's necessary to have multiple projects running on different doors.

**Comment by thevinge** [comment]
> 
> 
> It's not possible to have multiple instances of THorse in a single project. To have multiple instances, it's necessary to have multiple projects running on different doors.

I managed to implement the "multiple ports" feature into THorse. Are you interested in this feature?

**Comment by viniciussanchez** [comment]
Send us a pull request

**Comment by thevinge** [comment]
> 
> 
> Send us a pull request

I have some changes I would like to implement. I will send a pull request when the implementation is done.

**Comment by viniciussanchez** [comment]
Ok

**Comment by viniciussanchez** [comment]
Hello, how is the implementation?

**Comment by thevinge** [comment]
> Hello, how is the implementation?

I originally implemented the feature in version 1.78, however, after updating to version 2 my implementation broke. So I'm currently working on a new solution. I will let you know once I have succeeded.

**Comment by viniciussanchez** [comment]
Hello, how is the implementation?

**Comment by dliocode** [comment]
@thevinge, What would be the use case for implementing the ability to listen on more than one port?
