### ISSUE TITLE
How do i send content-type on response?

### ISSUE THREAD

**Issue by claudneysessa** [HashLoad/horse#143]
How do I send headers for responses?

Ex:

content-type: application / json

**Comment by claudneysessa** [comment]
Taking advantage of the doubt, how would I do to pass parameters worse queryString in the URL?

Example

localhot:98989/teste?id=1

**Comment by viniciussanchez** [comment]
You can test:

THorseHackResponse(Res).GetRawWebResponse.SetContentType

**Comment by viniciussanchez** [comment]
http://localhost:9000/products?name=iPhone

var LName: string;
LName := Req.Query['name'];

**Comment by claudneysessa** [comment]
> http://localhost:9000/products?name=iPhone
> 
> var LName: string;
> LName := Req.Query['name'];

This ok! perfect worked

**Comment by claudneysessa** [comment]
> You can test:
> 
> THorseHackResponse(Res).GetRawWebResponse.SetContentType

This one I didn't understand

**Comment by claudneysessa** [comment]
> You can test:
> 
> THorseHackResponse(Res).GetRawWebResponse.SetContentType

Based on your idea, I ended up going here and rescinded thanks for your attention!

THorseHackResponse(Res).GetWebResponse.SetCustomHeader('Content-Type','application/json');

**Comment by viniciussanchez** [comment]
😉

**Comment by claudneysessa** [comment]
All right!
Great tool!
I will make some presentation videos of it soon!

**Comment by viniciussanchez** [comment]
See this 
https://www.youtube.com/playlist?list=PL_YzAvjux_LZPLp1LGBESZvXuohP6I7HC
