### ISSUE TITLE
Problema ao passar uma data como parametro

### ISSUE THREAD

**Issue by afonsofoletto** [HashLoad/horse#148]
ao passa uma data como parâmetro esta retornando um erro de não encontrado.

**Comment by dliocode** [comment]
Pode colocar o teu código?

**Comment by CarlosHe** [comment]
Então, @dliocode, eu acompanhei de perto esse problema ocorrendo! Ele usa um URI Param com campo data! Mesmo a data com encode, ocorre o erro! Acredito que esteja fazendo o decode da URI antes de procurar pela rota!

Exemplo (data/**:data**/find ): data/**10%2F10%2F2020**/find

**Comment by dliocode** [comment]
Eu testei usando o RawPathInfo, quando vai pegar a informação do Params, está como 10%2F10%2F2020

**Comment by arvanus** [comment]
Olá, parece que ele realmente está fazendo o decode antes de analisar qual rota utilizar, daí acaba não achando a rota específica
Estou tendo o mesmo problema

**Comment by viniciussanchez** [comment]
Problema resolvido pessoal. 
Liberado na 2.0.4
![image](https://user-images.githubusercontent.com/16382981/98688384-8a9c0e80-2349-11eb-8ed7-c2db4215bd88.png)
