### ISSUE TITLE
Setar provider a ser usado.

### ISSUE THREAD

**Issue by chacalfloripa** [HashLoad/horse#149]
Implementar opção de setar o Provider a ser usado pelo Horse, com esta opção seria possível criar novos provider's sem a necessidade de alterar o core do Horse.

**Comment by viniciussanchez** [comment]
Bom dia, por curiosidade, qual provider você queria adicionar?

**Comment by chacalfloripa** [comment]
Recentemente eu criei o Daemon para Lazarus e enviei o PR, mas se existir a opção se setar o provider não precisaria alterar o core para incluir um novo tipo.  Outra aplicação seria usar um servidor HTTP diferente como Synapse por exemplo.

**Comment by viniciussanchez** [comment]
Boa tarde, depois de analisarmos melhor, achamos que não será muito viável essa ideia, visto que não surgem novos providers assim, afim de ter toda essa arquitetura... Por isso vamos fechar essa issue, e se um dia precisar abrimos novamente ok. Obrigado pela colaboração...
