### ISSUE TITLE
InitializeContentFields retornando erro  "Duplicates not allowed"

### ISSUE THREAD

**Issue by FranziniDev** [HashLoad/horse#151]
Ola, bom dia.

Após a inclusão desta função comecei a ter como resposta "Duplicates not allowed".

Ocorre quando utiliza o Body de um post e informa um Json Array - exemplo [{"controle":1}, {"controle":2}]

Quando envia um Objeto Json {} o problema não ocorre.

Será que perdi alguma outra Implementação e deixei de configurar algo de forma correta ? ou é um caso a ser corrigido mesmo ?

Por enquanto para poder utilizar desta forma estou comentando o trecho, como mostrado abaixo :

constructor THorseRequest.Create(AWebRequest: {$IF DEFINED(FPC)}TRequest{$ELSE}TWebRequest{$ENDIF});
begin
FWebRequest := AWebRequest;
InitializeQuery;
InitializeParams;
//// InitializeContentFields;
InitializeCookie;
end;

**Comment by viniciussanchez** [comment]
Obrigado por reportar @FranziniDev
