### ISSUE TITLE
MemoryLeaks - Octet-Stream

### ISSUE THREAD

**Issue by sufurujhin** [HashLoad/horse#154]
******Método para Post*******
 
THorse.Post('/backup',
      procedure(Req: THorseRequest; Res: THorseResponse; Next: TProc)
      var
        Stream: TmemoryStream;
      begin
          Stream := Req.Body<TmemoryStream>;
           if Stream <> nil then
              Stream.SaveToFile(Dir);
  end);

Recebo o arquivo Stream do módulo Client salvo em disco sem problemas, mas quando
se trata de a API receber arquivos maiores e a transferência é paralela com duas ou mais, caso seja dois, um dois arquivos não é liberado de memória, ou seja, apenas o ultimo é liberado de memória,  é como  o Horse criasse apenas a instancia da requisição
e utilizasse uma variável stream para  todas as requisições.
Chega uma requisição  Stream = Stream_Client1, próxima requisição paralela Stream = Stream_Client2, com isso mesma variável recebeu dois valores sendo assim o endereço de memória(ponteiro) do primeiro stream foi perdido ficando em memória. Com isso o consumo de memoria aumenta, causando Out of Memory e no lado do Client Conexão abortada entre outros erros, segue print da Memoryleak dos arquivos perdidos em memoria. Primeiro erro, módulo Client, erro inferior Módulo Servidor ao finalizar a aplicação. Sendo assim essa foi minha analise quanto o que ocorre com varias transferências.
ATENÇÂO: o mesmo só ocorre em transferências simultânea, a mesma executada em sequencia após a outra não ocorre. 

Informação do Servidor:
Dell R620 + 128GB de Ram
Sistema Operacional Windows Server 2019 Essentials
Sendo que a API roda em uma VM com 16GB de Ram e 4 Core.
![image](https://user-images.githubusercontent.com/46231089/102342689-5cc56d80-3f78-11eb-9526-2c8df6b311ae.png)

**Comment by sufurujhin** [comment]
e caso eu libere o objeto de memoria após a gravação em disco, ocorre uma exceção pelo objeto não existe não existir em memória. ou seja, o ultimo objeto.

**Comment by CarlosHe** [comment]
Consegue anexar um exemplo mínimo do teu código?

**Comment by sufurujhin** [comment]
![image](https://user-images.githubusercontent.com/46231089/103406455-86b28e80-4b39-11eb-8023-c500dc1cfb6d.png)
![image](https://user-images.githubusercontent.com/46231089/103406471-8f0ac980-4b39-11eb-90ec-7fdd4aae686f.png)

**Comment by sufurujhin** [comment]
Bom dia, para resolver essa questão coloquei a Aplicação em 64bits, resolveu, mas as vezes fica algum objeto em memoria , o erro ocorre devido a Out of Memory, então quando ocorre essa exceção, o TStream n é liberado de memoria o que ocorre muito em 32bits.

**Comment by sufurujhin** [comment]
> Consegue anexar um exemplo mínimo do teu código?

.

**Comment by CarlosHe** [comment]
A instância da stream é única, o problema não seria conflito de stream, cada request tem sua própria stream.

Mas olhando o fonte aqui, achei uma possível limitação do middleware octet-stream que pode ser inclusive o causador do teu erro. Eu vou fazer umas melhorias no middleware e pedir para você verificar se houve a correção do teu problema. Lembrando que não seria exatamente um bug, apenas uma limitação do middleware.

**Comment by sufurujhin** [comment]
> A instância da stream é única, o problema não seria conflito de stream, cada request tem sua própria stream.
> 
> Mas olhando o fonte aqui, achei uma possível limitação do middleware octet-stream que pode ser inclusive o causador do teu erro. Eu vou fazer umas melhorias no middleware e pedir para você verificar se houve a correção do teu problema. Lembrando que não seria exatamente um bug, apenas uma limitação do middleware.

Entendo, a limitação se dá devido a ao sistema ser 32bits, mas quanto houver uma exceção, o objeto stream deveria ser removido de memoria mesmo com o erro n? pq se ocorre essa exceção ao receber esse objeto e nessa hora ocorre o Out of Memory então o objeto possivelmente não foi removido de memoria, não cheguei a verificar se ele fica  mas só de olhar o gerenciador de tarefa percebe-se que ficou em memoria.

**Comment by CarlosHe** [comment]
Eu testei aqui para causar o Out of Memory em x32. Basta enviar um arquivo maior que 4gb, mas não apresentou memory leak.

**Comment by sufurujhin** [comment]
envie dois ao mesmo tempo, ou seja duas requisições 

> Eu testei aqui para causar o Out of Memory em x32. Basta enviar um arquivo maior que 4gb, mas não apresentou memory leak.

**Comment by sufurujhin** [comment]
apenas uma requisição não ocorre o erro.

**Comment by CarlosHe** [comment]
Eu vou montar um exemplo aqui.

**Comment by sufurujhin** [comment]
> envie dois ao mesmo tempo, ou seja duas requisições
> 
> > Eu testei aqui para causar o Out of Memory em x32. Basta enviar um arquivo maior que 4gb, mas não apresentou memory leak.

envie duas requisições, dois arquivos diferentes simultâneo.

**Comment by viniciussanchez** [comment]
Boa tarde...
O problema aqui ainda está ocorrendo?

**Comment by dliocode** [comment]
@sufurujhin O problema ainda acontece?
