### ISSUE TITLE
[ 2 DÚVIDAS] - Horse

### ISSUE THREAD

**Issue by danilocastelhano1** [HashLoad/horse#158]
Boa tarde, preciso criar uma api, e meu cliente quer que seja em Horse usando JWT, porém em 2 endpoints não vai ter autenticação, que é o que vai retornar o JWT, GET ```/gettoken/``` e um POST ```/createuser/``` , como seria esses 2 endpoints? o resto vai ter autenticação JWT, procurei antes de postar aqui e não achei nada relacionado

Duvida 2, seria um console Application mesmo, pelo que mapeamos, vai ter uns 60 endpoints, ele ficaria um embaixo do outro mesmo ou tem como separar melhor? sei la colocar um método que retorna so endpoints de pagamentos: ListEndpointsPagto() e outro de usuário: ListEndpointsUsers() ficando + ou - assim:
```
function ListEndpointsUsers()
var
  retornarEndpoints: nao sei o tipo;
begin
   retornarEndpoints :=  retornarEndpoints + THorse.Get('/ping',
    procedure(Req: THorseRequest; Res: THorseResponse; Next: TProc)
    begin
      Res.Send('pong');
    end);
    
     retornarEndpoints :=  retornarEndpoints + THorse.Post('/test',
    procedure(Req: THorseRequest; Res: THorseResponse; Next: TProc)
    begin
      Res.Send('pong');
    end);
    result :=  retornarEndpoints;
end;
ListEndpointsUsers();
.....
```
hj na documentação é um "GET" embaixo do outro né?
```
THorse.Get('/ping',
    procedure(Req: THorseRequest; Res: THorseResponse; Next: TProc)
    begin
      Res.Send('pong');
    end);
THorse.Post('/test',
    procedure(Req: THorseRequest; Res: THorseResponse; Next: TProc)
    begin
      Res.Send('pong');
    end);
.....
```

**Comment by viniciussanchez** [comment]
Este projeto tem a parte de trabalhar endpoint com e sem JWT: https://github.com/HashLoad/kanbana-api
Você pode pegar ele como exemplo.

![image](https://user-images.githubusercontent.com/16382981/103576321-b8b54f00-4eb1-11eb-9522-d588bfd07525.png)

Aqui você pode especificar qual o middleware que ele vai usar, se é JWT, Basic, ou se não passar nada ele não terá autenticação. Você também pode definir uso de middlewares por grupo de rotas. Na versão 2.0 você consegue agrupar rotas.

**Comment by viniciussanchez** [comment]
> Duvida 2, seria um console Application mesmo, pelo que mapeamos, vai ter uns 60 endpoints, ele ficaria um embaixo do outro mesmo ou tem como separar melhor? sei la colocar um método que retorna so endpoints de pagamentos: ListEndpointsPagto() e outro de usuário: ListEndpointsUsers() ficando + ou - assim:

Isso também da pra pegar como exemplo o projeto acima.

**Comment by danilocastelhano1** [comment]
Nossa, que massa, Pra eu passar um metodo sem autenticação é só eu escrever assim?

```
THorse.GET('/register', nill, DoRegistration);
```
ai no login usaria:
```
THorse.GET('/register', BasicAuthorization(), DoLogin);
```

**Comment by viniciussanchez** [comment]
Basicamente isso, mas existe outras formas tambem, como eu disse, da pra definir middlewares por grupos de rotas como foi apresentado no vídeo de lançamento da versão 2.0 do Horse.

https://youtu.be/CY1wLVrVmkI

**Comment by danilocastelhano1** [comment]
Massa, vou assistir e implementar no meu cliente, muito obrigado, vcs foram muito solicitos
