### ISSUE TITLE
Erro ao Compilar Projeto Horse

### ISSUE THREAD

**Issue by nfers** [HashLoad/horse#16]
Estou realizando a instalação do framework, inclui no source path do delphi, porem ao compilar o projeto ocorre o seguinte erro: 

**[dcc32 Error] E2223 $DENYPACKAGEUNIT 'Web.WebBroker' cannot be put into a package,**

Uso o Delphi 10.3

Podem me ajudar?

**Comment by viniciussanchez** [comment]
Oi @nfers ...
Porque não usa o [Boss](https://github.com/HashLoad/boss) para instalação?  Muito mais simples...

**Comment by nfers** [comment]
Oi @viniciussanchez, fiz pelo Boss, deu certo. Obrigada.

**Comment by vhanla** [comment]
I installed using boss and it throws the same error "Web.Webroker"

**Comment by viniciussanchez** [comment]
@vhanla What version of Delphi?

**Comment by vhanla** [comment]
10.3.3

**Comment by snakeice** [comment]
You trying compile into bpl?

**Comment by vhanla** [comment]
Oh, I didn't notice that, samples work well.

**Comment by L1NDS0N** [comment]
> You trying compile into bpl?

Não é possível compilar dentro de uma .bpl?
Estou tendo o mesmo erro, mas, o meu cenário é dentro de uma bpl.

**Comment by viniciussanchez** [comment]
Não que não seja possível, mas é que o projeto do Horse em si existe uma bpl que usamos apenas para compilar as units e saber se está tudo certo. Mas muitos quando baixam os fontes, tentam instalar essa bpl. E não é assim que o Horse funciona. Essa bpl é apenas para nos auxiliar no desenvolvimento. Nada de mais. Ela não tem outra finalidade.

**Comment by L1NDS0N** [comment]
Acho que esse não é o meu caso, eu instalo a dependência (horse) com o boss, no meu pacote .bpl, e obtenho o mesmo erro quando tento compilar esse pacote ou tento utilizar em outro pacote aquela unit com a dependência do horse.
