### ISSUE TITLE
Usar no Lazarus

### ISSUE THREAD

**Issue by liviosa** [HashLoad/horse#169]
Queria uma dica de como posso usar o Horse e seus middlewares no Lazarus 2.0.10 com Linux(Kali)

**Comment by viniciussanchez** [comment]
Boa tarde, você já faz parte do nosso grupo no Telegram?
https://t.me/hashload

Lá tem bastante pessoas já usando o Horse com o Lazarus que podem te ajudar. 
Mas qual seria a sua dúvida realmente?

Temos um vídeo no Youtube também onde mostramos a compilação para Lazarus no lançamento da versão 2.0 do Horse.

Na pasta Samples do Horse, temos também projetos de exemplos tanto com Delphi como Lazarus;
