### ISSUE TITLE
DOCUMENTATION???!

### ISSUE THREAD

**Issue by Oscar-Silva** [HashLoad/horse#17]
Hi guys, do you make a very good framework for work in web applications with delphi, but, this framework donsen't have a full documentation.

https://romantic-lalande-2d106d.netlify.com/pt-br/guide/index.html#Pronto-para-Mais

this is don't have nothing to make a real server in real situations of work :(

**Comment by viniciussanchez** [comment]
https://www.youtube.com/watch?v=_HOo2X0zWQ4&t=2655s
