### ISSUE TITLE
Bug Routes.Prefix  com Routes.RegisterRoute

### ISSUE THREAD

**Issue by antoniojmsjr** [HashLoad/horse#175]
Quando utilizado dessa forma, a criação do caminho do recurso está concatenando o prefix e o path sem a barra da URL ficando assim nesse exemplo: 

http://localhost:9000/v1ping

A rotina Prefix remove o caractere '/' e quando chamado a função GetQueuePath a uma concatenação Prefix + Path.
Class: THorseRouterTree

THorse.Routes.Prefix('v1/');
THorse.Routes.RegisterRoute(TMethodType.mtGet, 'ping', GetPing);

![image](https://user-images.githubusercontent.com/20980984/112499442-3a58a280-8d66-11eb-81f3-7ac5992c5137.png)

**Comment by viniciussanchez** [comment]
No caso acredito que esteja faltando uma validação assim:

```pascal
if AUsePrefix then
begin
  if not APath.StartWith('/') then
    APath := FPrefix + '/' + APath
  else
    APath := FPrefix + APath;
end;
```

**Comment by antoniojmsjr** [comment]
@viniciussanchez perfeito, isso mesmo.

**Comment by viniciussanchez** [comment]
Se quiser contribuir com o projeto, implemente esse código e nos envie um Pull Request ;)

**Comment by antoniojmsjr** [comment]
> Se quiser contribuir com o projeto, implemente esse código e nos envie um Pull Request ;)

ok
