### ISSUE TITLE
SendRedirect não esta mais funcionando.

### ISSUE THREAD

**Issue by giorgiobazzo** [HashLoad/horse#181]
Até a versão 2.0.10 ao usar o THorseHackResponse e SendRedirect para redirecionar uma requisição para outra rota está 
funcionando como esperado.

Testei o mesmo middleware abaixo com as versões 2.0.11, 2.0.12, 2.0.13 e a master, e em nenhuma dessas SendRedirect funcionou. Voltando a versão para 2.0.10 o redirecionamento volta a funcionar.

```
procedure DoRedirect(Req: THorseRequest; Res: THorseResponse; Next: TProc);
var
  LWebRequest : TWebRequest;
  LWebResponse : TWebResponse;
  LPath : string;
begin
  LWebRequest := THorseHackRequest(Req).GetWebRequest;
  LWebResponse := THorseHackResponse(Res).GetWebResponse;
  LPath := LWebRequest.InternalPathInfo.ToLower;
  if LPath.Equals('/') or LPath.Equals('/doc') then
  begin
    Next();
    LWebResponse.SendRedirect('/doc/html');
  end
end;
```

**Comment by viniciussanchez** [comment]
Nas versões novas foi criado o Req.RawWebRequest e o Res.RawWebResponse
Você tentou usar eles ao invés de usar o THorseHackRequest e THorseHackResponse?

**Comment by giorgiobazzo** [comment]
Testei com a versão 2.0.13, usando Res.RawWebResponse no lugar de THorseHackResponse(Res).GetWebResponse e mesmo assim não funcionou.

**Comment by viniciussanchez** [comment]
Boa tarde... isso aqui você chegou a resolver o problema?

**Comment by giorgiobazzo** [comment]
Bom dia @viniciussanchez último teste que fiz foi com a versão 2.0.13 e não estava funcionando.

**Comment by dliocode** [comment]
Olá @giorgiobazzo , eu fiz uma [PR que corrige o SendRedirect](https://github.com/HashLoad/horse/pull/200) consegue testar com essa PR. Depois dá um feedback se deu tudo certo para que possamos fazer o merge com o projeto atual!
