### ISSUE TITLE
Servidor não responde após requisição sem content-type

### ISSUE THREAD

**Issue by ewertont** [HashLoad/horse#182]
Olá pessoal!
Fazendo alguns testes percebi que após enviar uma requisição sem content-type no header o servidor horse trava e não responde mais, mesmo colocando o content-type.

Servidor rodando normalmente:
![image](https://user-images.githubusercontent.com/7762971/117513547-51470300-af68-11eb-9547-9abda22a7188.png)

Post:
![image](https://user-images.githubusercontent.com/7762971/117513168-8f8ff280-af67-11eb-8751-6d9fc5ef992a.png)

Após o Post:
![image](https://user-images.githubusercontent.com/7762971/117513400-fa412e00-af67-11eb-81dc-1fbb276ba1c8.png)

**Comment by viniciussanchez** [comment]
Boa tarde
Você está utilizando algum middleware?
Tem algum projeto básico para nos passar que aconteça o problema?

**Comment by dliocode** [comment]
Olá @ewertont , você ainda está com problema? Eu fiz um pequeno teste e não tive nenhum problema..

![image](https://user-images.githubusercontent.com/54585337/132879540-147707f1-cfa8-499d-ab5b-4676bae588d6.png)

**Comment by dliocode** [comment]
Fechado por falta de resposta!
