### ISSUE TITLE
Problema ao alterar a porta do servidor.

### ISSUE THREAD

**Issue by giorgiobazzo** [HashLoad/horse#188]
Passos para reproduzir.

1 - THorse.Listen(3000); //Servidor respondendo na porta 3000

2 - THorse.StopListen; //Servidor para de responder

3 - THorse.Listen(4000); //O servidor ainda continua respondendo na porta 3000 e não na porta 4000 como esperado.

Debugando a unit Horse.Provider.Console.pas na class procedure InternalListen cheguei no bloco:

```
    if FHost <> GetDefaultHost then
    begin
      LIdHTTPWebBrokerBridge.Bindings.Clear;
      LIdHTTPWebBrokerBridge.Bindings.Add;
      LIdHTTPWebBrokerBridge.Bindings.Items[0].IP := FHost;
      LIdHTTPWebBrokerBridge.Bindings.Items[0].Port := FPort;
    end;
```

Pelo que pude ver como o FHost não mudou este "IF" impede que os Bindings sejam redefinidos para a nova porta e por isso o servidor ainda continua respondendo na porta 3000 mesmo depois do StopListen e Listen(4000).
Eu removi o "IF" deixando a redefinição dos Bindings sempre sendo executada, e isso parece ter resolvido o problema.

Minha dúvida é se isso pode gerar algum outro tipo de problema?

**Comment by viniciussanchez** [comment]
Eu vi que esse mesmo tratamento acontece nas seguintes units:

![image](https://user-images.githubusercontent.com/16382981/122117117-dc83a600-cdfc-11eb-8cbe-270518f23c84.png)

Eu fiz um teste aqui também removendo o IF e aparentemente não tive nenhum problema.
Analisando as units de compatibilidade com o Lazarus, lá não tem esse tratamento (embora o componente utilizado é diferente).

![image](https://user-images.githubusercontent.com/16382981/122117265-08069080-cdfd-11eb-95b9-a6b09967f64f.png)
