### ISSUE TITLE
Erro ao compilar pacote horse

### ISSUE THREAD

**Issue by schrsistemas** [HashLoad/horse#189]
Ao tentar compilar o pacote "horse" no delphi rio comunity ocorre o seguinte erro:

[dcc32 Error] E2223 $DENYPACKAGEUNIT 'Web.WebBroker' cannot be put into a package

**Comment by viniciussanchez** [comment]
Bom dia @schrsistemas , o Horse não é para ser instalado como pacote clicando com o botão direito e mandar dar um build / install. O Horse para instalar ou você baixa os fontes e adiciona no seu projeto as units ou então no library path ou search path. Ou faça o uso do Boss como gerenciador de dependências para fazer a instalação utilizando o comando `boss install horse`

**Comment by schrsistemas** [comment]
Boa noite, tudo certo?
Até tentei via "boss" mais ai estou tento um segundo problema, alguns pacotes durante compilação ocorrem falha.

`
D:\Desenvolvimento\Componentes\HashLoad>boss install -g horse
[INFO ] Installing modules in project path
[INFO ] Building cache files...
[INFO ] Updating cache of dependency boss-ide
[INFO ] Updating cache of dependency bpl-identifier
[INFO ] Updating cache of dependency delphi-docker
[INFO ] Updating cache of dependency horse
[INFO ] Updating cache of dependency boss
[INFO ] Installing modules
[INFO ] Processing dependency boss-ide
[INFO ]   Detected semantic version. Using version 1.4.1
[INFO ] Processing dependency bpl-identifier
[INFO ]   Detected semantic version. Using version 1.0.6
[INFO ] Processing dependency delphi-docker
[INFO ]   Detected semantic version. Using version 1.0.3
[INFO ] Processing dependency horse
[INFO ]   horse already updated
[INFO ] Processing dependency boss
[INFO ]   boss already updated
[INFO ] Processing module DOSCommand
[INFO ] Building cache files...
[INFO ] Installing modules
[INFO ] Processing module boss
[WARN ]   boss.json not exists in boss
[INFO ] Processing module boss-ide
[INFO ] Building cache files...
[INFO ] Updating cache of dependency doscommand
[INFO ] Installing modules
[INFO ] Processing dependency doscommand
[INFO ]   Detected semantic version. Using version 1.0.3
[INFO ] Processing module bpl-identifier
[INFO ] Building cache files...
[INFO ] Installing modules
[INFO ] Processing module delphi-docker
[INFO ] Building cache files...
[INFO ] Updating cache of dependency DOSCommand
[INFO ] Installing modules
[INFO ] Processing dependency DOSCommand
[INFO ]   DOSCommand already updated
[INFO ] Processing module horse
[INFO ] Building cache files...
[INFO ] Installing modules
[INFO ] Compiling units
[INFO ] Building doscommand
[INFO ]   Building DOSCommandDR.dproj
[ERROR]   - Failed to compile, see C:\Users\Daniel\.boss\modules\99ad0898c06b13dadfed02ed6a122b8a\modules\doscommand\Packages\Delphi\build_boss_DOSCommandDR.log for more information
[INFO ]   Building DOSCommandDD.dproj
[ERROR]   - Failed to compile, see C:\Users\Daniel\.boss\modules\99ad0898c06b13dadfed02ed6a122b8a\modules\doscommand\Packages\Delphi\build_boss_DOSCommandDD.log for more information
[INFO ] Building bpl-identifier
[INFO ]   Building BplIdentifier.dproj
[ERROR]   - Failed to compile, see C:\Users\Daniel\.boss\modules\99ad0898c06b13dadfed02ed6a122b8a\modules\bpl-identifier\build_boss_BplIdentifier.log for more information
[INFO ] Building delphi-docker
[INFO ]   Building DelphiDocker.dproj
[ERROR]   - Failed to compile, see C:\Users\Daniel\.boss\modules\99ad0898c06b13dadfed02ed6a122b8a\modules\delphi-docker\build_boss_DelphiDocker.log for more information
[INFO ] Building boss-ide
[INFO ]   Building boss_ide.dproj
[ERROR]   - Failed to compile, see C:\Users\Daniel\.boss\modules\99ad0898c06b13dadfed02ed6a122b8a\modules\boss-ide\build_boss_boss_ide.log for more information
[INFO ] Success!
`

**Comment by schrsistemas** [comment]
Funcionou! Obrigado...
