### ISSUE TITLE
Inconsistent behavior across THorseRequest.Initialize* methods

### ISSUE THREAD

**Issue by arvanus** [HashLoad/horse#191]
Hi!
Looking at:
https://github.com/HashLoad/horse/blob/9f8d2d8e243cab8a267b078bfd2f73f6aff8ec02/src/Horse.HTTP.pas#L156-L203
I found that `THorseRequest.InitializeContentFields` lowercases the parameters name, while `InitializeQuery`, `InitializeParams` and `InitializeCookie` don't
I would suggest to change all methods to the same behavior (preferentially allowing the user do choose in the initialization like `Dataset.Serialize` `TCaseNameDefinition = (cndNone, cndLower, cndUpper, cndLowerCamelCase, cndUpperCamelCase);` or something like this)
I see this as a breaking change behavior, so this change would occur only to Horse 3.0.0, what do you think?

Thanks!

**Comment by arvanus** [comment]
The ideal would be to make the parameters case insensitive, like `query.paramByName('pAraMNAmE')`, but as Horse uses `  TDictionary<TKey,TValue>` I really don't know if it's easy to change

**Comment by arvanus** [comment]
Ops, looks like https://stackoverflow.com/questions/1611636/how-to-create-a-case-in-sensitive-tequalitycomparer-for-tdictionary solves the problem 😄 
using `TDictionary<string, string>.Create(TIStringComparer.Ordinal)` works! (just tested with Delphi 10.4.2
I just don't know if it's compatible with Lazarus (don't use Lazarus)

**Comment by viniciussanchez** [comment]
Thank you, let's take a closer look

**Comment by arvanus** [comment]
If you want, I can pull request a patch with respective change `.Create(TIStringComparer.Ordinal)`
