### ISSUE TITLE
Exemplo console lazarus disparando exceção

### ISSUE THREAD

**Issue by jcbritobr** [HashLoad/horse#194]
Olá, Fui executar um exemplo desse repositório com lazarus 2.0.12 e freepascal 3.2.0. O exemplo **console** dispara a seguinte exception:

![image](https://user-images.githubusercontent.com/6579862/126692359-335984e0-9008-4478-8a71-9aa305d7f505.png)

Existe algum arquivo que deveria estar presente nesse projeto?

**Comment by dliocode** [comment]
Ola @jcbritobr eu fiz uma correção referente a esse problema, pode fazer uma teste pra mim?

Para este teste não dá para usar o Boss.. Tem que baixar o projeto do Horse!

Depois me dá um feedback sobre isso, aguardo!
