### ISSUE TITLE
Lowercase em requisições com multipart/form-data

### ISSUE THREAD

**Issue by alexsro** [HashLoad/horse#197]
Requisições com multipart/form-data convertem as chaves em lowercase, oque fazer com  que ao utilizar a conversão de json para object não encontre propriedades quando se esta utilizando camelcase. Abaixo esta a parte do código que faz a conversão e fica localizada em Horse.HTTP.

procedure THorseRequest.InitializeContentFields;
var
  I: Integer;
begin
  FContentFields := THorseList.Create;
  if (not CanLoadContentFields) then
    Exit;
  for I := 0 to Pred(FWebRequest.ContentFields.Count) do
  begin
    FContentFields.AddOrSetValue(LowerCase(FWebRequest.ContentFields.Names[I]),
      FWebRequest.ContentFields.ValueFromIndex[I]);
  end;
end;

**Comment by dliocode** [comment]
Olá Alex, não entendi sua dúvida!

Tem algum exemplo de como você manda as informações e de como você trata elas no teu código?
