### ISSUE TITLE
Write / Write - Application VCL Form

### ISSUE THREAD

**Issue by renanfrancisodasilva** [HashLoad/horse#20]
I did not understand the use of the Write and Read line in Horse.pas.
Because when used in conjunction with the Service or VCL, an error occurs.
For these screen exits, wouldn't it be better to pass a function to Log Horse?
If something needs to be displayed, the passed function is responsible for the display / translation, which would generate console and VCL compatibility.

**Comment by ulissespsm2** [comment]
You can solve the problem put ConsoleAlloc command before start
