### ISSUE TITLE
MultiThread

### ISSUE THREAD

**Issue by lucasbelkys** [HashLoad/horse#201]
Bom dia!
Estou prestes a desenvolver um emissor de nota fiscal eletrônica utilizando o horse, mas me deparei com uma dúvida importantíssima: Cada chamada em um endPoint representa uma Thread a parte? Ou preciso implementar isso?

Grato desde já por qualquer ajuda!

**Comment by viniciussanchez** [comment]
Cada requisição é uma thread separada
