### ISSUE TITLE
Manage cookie

### ISSUE THREAD

**Issue by acarlomagno** [HashLoad/horse#203]
Hi,
I need to write and read a cookie on client browser when the user access to a endpoint
I use this way to write the cookie:
    var
      s: TStringlist;
    begin

      s := TStringlist.Create;
      s.Add('color=yellow');
      Res.RawWebResponse.SetCookieField(s, 'localhost', '/', now + 1, false);

but how to read the cookie ? ... in the Req.RawWebRequest.CookieFields I habe all cookie ... can I read a single cookie and all data of cookie ?

or exist another way to manage cookies ?
thanks
Antonello

**Comment by dliocode** [comment]
Hi @acarlomagn, 

How to read a simple cookie?
`Req.RawWebRequest.CookieFields.Values['color']; // output yellow`

**Comment by dliocode** [comment]
Ok?

**Comment by acarlomagno** [comment]
Hi @dliocode 
I thought I had tried all the properties ... but I was wrong reading.
thanks it works perfect
