### ISSUE TITLE
Problema com propriedade Headers com ISAPI e IIS10

### ISSUE THREAD

**Issue by ghmarcheti** [HashLoad/horse#204]
Olá, 
Estou trabalhando em um projeto em ISAPI no IIS10 que recebe via HEADERS tokens de acesso.
Ao rodar a aplicação em CONSOLE a propriedade THorseRequest.Headers retornar corretamente o valor do HEADER. 
Contudo ao rodar em ISAPI a mesma chamada retorna uma string vazia.

Fiz um teste que encontrei em outro forum que orientou no caso de ISAPI a chamar a função TWebRequest.GetFieldByName passando "HEADER_" antes do nome do HEADER do request e aparentemente funcionou assim:

Req.RawWebRequest.GetFieldByName('HEADER_'+nome_header)

Alguém saberia dizer se estou fazendo algo errado ou é uma particularidade do ISAPI?

**Comment by dliocode** [comment]
Oi @ghmarcheti ,

Vou recomendar você usar da seguinte forma: 
Req.Headers[nome_header] ou Req.Headers['HEADER_'+ nome_header]

Sobre a questão de colocar o HEADER_ no início é algo do ISAPI mesmo!

**Comment by dliocode** [comment]
ok?

**Comment by ghmarcheti** [comment]
Ola!
Desculpe a demora.
Obrigado @dliocode pelas informações.
Aqui fiz a diferenciação testando a função isLibrary e deu certo.

Mas como sugestão no projeto, não seria legal fazer este teste de ISAPI na função GetHeaders da Unit Horse.HTTP através da função IsLibrary ou até através da Condicional Define HORSE_ISAPI pois percebi que alguns Middlewares utilizam Req.Headers.

**Comment by dliocode** [comment]
Obrigado pelo feedback, estaremos analisando essa situação!
