### ISSUE TITLE
Implementation Cookie and MethodType

### ISSUE THREAD

**Issue by BenevalJr** [HashLoad/horse#21]
My implementation of Cookie and MethodType for THorseRequest and THorseResponse
[Horse.HTTP.txt](https://github.com/HashLoad/horse/files/4098565/Horse.HTTP.txt)

**Comment by viniciussanchez** [comment]
I liked GetMethodType.
But CookieFields you could implement similar to Query by returning a THorseList to follow the same pattern. Not to mention the facilities that using TDictionary brings to the application.
Congratulations for the initiative...
