### ISSUE TITLE
[dcc32 Error] E2223 $DENYPACKAGEUNIT 'Web.WebBroker' cannot be put into a package

### ISSUE THREAD

**Issue by kabiri** [HashLoad/horse#215]
can not install it on Delphi 11
Error:
[dcc32 Error] E2223 $DENYPACKAGEUNIT 'Web.WebBroker' cannot be put into a package

**Comment by rafael-figueiredo-alves** [comment]
Hi, @kabiri 

I think it would be much better if you used Boss to install Horse as a dependency on your project than installing it on Delphi. Don't you think so?

**Comment by kabiri** [comment]
[WARN ] Please restart your console after complete.
[INFO ] Installing modules in project path
[INFO ] Building cache files...
[INFO ] Updating cache of dependency horse
[INFO ] Downloading dependency github.com/hashload/horse
[INFO ] Installing modules
[INFO ] Processing dependency horse
[WARN ] Tag not found , using semantic now...
[INFO ]   Detected semantic version. Using version v2.0.14
[INFO ] Processing module horse
[INFO ] Building cache files...
[INFO ] Installing modules
[INFO ] Compiling units
[INFO ] Building horse
[INFO ] Success!

But now it does not work at all
[dcc32 Fatal Error] untMainServer.pas(25): F2613 Unit 'horse' not found.

**Comment by viniciussanchez** [comment]
Hi, to install Horse you don't need to compile the package.
You can install:
1 - Using Boss;
2 - Adding to the project's Search path;
3 - Adding to library path;
4 - Adding the units to the project
