### ISSUE TITLE
files not found

### ISSUE THREAD

**Issue by kabiri** [HashLoad/horse#216]
this file  not found
Horse.Jhonson 
RESTRequest4D.Request

**Comment by rafael-figueiredo-alves** [comment]
Hi, @kabiri. Let me ask you something. Have you downloaded the source of these two projects? Horse.jhonson is from a middleware you can use with Horse to make it possible to use JSON in your responses. RESTRequest4D.Request is a unit from the project RESTRequest4D, and it's not part of the Horse bundle. What's exactly your problem?

**Comment by kabiri** [comment]
I ran the example "horse \ tests \ src" and it did not find these files.
I also added the path in Delphi

> Hi, @kabiri. Let me ask you something. Have you downloaded the source of these two projects? Horse.jhonson is from a middleware you can use with Horse to make it possible to use JSON in your responses. RESTRequest4D.Request is a unit from the project RESTRequest4D, and it's not part of the Horse bundle. What's exactly your problem?

**Comment by viniciussanchez** [comment]
Jhonson: https://github.com/HashLoad/jhonson
RESTRequest4D.Request: https://github.com/viniciussanchez/RESTRequest4Delphi
