### ISSUE TITLE
Visualização memory leaks da aplicação

### ISSUE THREAD

**Issue by fabiohmribeiro** [HashLoad/horse#229]
Olá gostaria de tirar uma dúvida: 
Qual a melhor forma de de enxergar, visualmente, na compilação, os memory leaks da aplicação?
Já tentei adicionado apenas o reportmemoryleaksonshutdown e forcei, porém sem retorno.

**Comment by fardeadbr** [comment]
Se for uma aplicação console, execute ela direto pelo terminal.

**Comment by gabrielbaltazar** [comment]
Bom dia,  pra aplicação console você deve setar os IsConsole := False pra que 

![Leak](https://user-images.githubusercontent.com/9014016/148536308-897ae962-538d-443e-86f3-fa4bb7e22ad8.jpg)
