### ISSUE TITLE
ISAPI Error

### ISSUE THREAD

**Issue by nilcemar** [HashLoad/horse#23]
I'm trying to use ISAPI module on IIS10 (windows 10 or Windows Server 2019)
With a simple demo supplied this error is showed.

`Internal Application Error
Unbalanced stack or queue operation`

Creating a dll isapi using REST Server Datasnap wizard works ok.

**Comment by battecnologia** [comment]
We have a issue with this too. We can't host our app in DLL ISAPI with IIS using horse? Anybody has a solution?

**Comment by viniciussanchez** [comment]
https://www.youtube.com/watch?v=qIjK-xV3OTE&t=95s
14:20 min I show how to compile on horse

**Comment by battecnologia** [comment]
Solved... "The error Internal Application Error Unbalanced stack or queue operation" occur because components of GUI for wait dialog of Firedac.. remove the uses clauses and compile in 32 bits works 100%. Thanks for support.

`Firedac units tested 100% with Horse and ISAPI:
     FireDAC.Phys.MySQLDef, FireDAC.Stan.Intf, FireDAC.DApt,FireDAC.ConsoleUI.Wait,
     FireDAC.Phys, FireDAC.Phys.MySQL, FireDAC.Stan.Error, FireDAC.Stan.StorageBin,
     FireDAC.Phys.Intf, FireDAC.Stan.Def, Data.DB, FireDAC.Comp.Client, FireDAC.Stan.Param,FireDAC.Stan.Async`
