### ISSUE TITLE
Port with HTTPS not listening

### ISSUE THREAD

**Issue by davibobsin** [HashLoad/horse#231]
Creating an API without enabling HTTPS, after calling THorse.Listen, my system always bind the port and show it is listening (using netstat). However, in some cases, HTTPS fails to bind the port. It seems to be some kind of timing issue because adding some sleeps on code, after configuring certificates for THorse, it seems to work. Someone had some similar problems or someone knows about some special care, when using HTTPS with horse?

**Comment by KingCodeCsharp** [comment]
Hi davibobsin!
As far as I know, https uses a specific port, 443, maybe that's the problem.

**Comment by viniciussanchez** [comment]
No... can you show us how you're doing it?
