### ISSUE TITLE
Horse ISAPI

### ISSUE THREAD

**Issue by kabiri** [HashLoad/horse#239]
Hi
i update Horse today
when i comple my old project get error in Unit Horse line 41
{$IF DEFINED(HORSE_ISAPI)}
  THorseProvider = Horse.Provider.ISAPI.THorseProvider<THorse>;

Error : [dcc32 Error] Horse.pas(41): E2003 Undeclared identifier: 'THorseProvider<>'

**Comment by viniciussanchez** [comment]
Strange... so far we haven't had anyone with this problem.

**Comment by viniciussanchez** [comment]
Did you set the build directive?

**Comment by kabiri** [comment]
Yes i add HORSE_ISAPI in Conditional defines
before update horse it work fine in ISAPI
