### ISSUE TITLE
A versão 3.0.1 tá quebrando algumas importações

### ISSUE THREAD

**Issue by L1NDS0N** [HashLoad/horse#244]
Não sei dizer o que ocorreu de fato, 
mas algumas coisas que percebi após atualização é que o dataset-serialize não está sendo importado, ou não é compilado de forma correta, aparentemente o construtor do EHorseException também mudou, aceitando menos argumentos.
Tem a ver com algum novo formato de uso?

**Comment by viniciussanchez** [comment]
Quanto ao DataSet-Serialize, nao tem nada a ver com o Horse acredito. Eles nem fazem ligação. 
Quanto ao EHorseException mudou da versão 2 para a 3 do Horse. Antigamente existia vários overloads do método Create do EHorseException. Agora usamos fluent interface e ficou mais claro cada parâmetro que está sendo informado. Pra usar a forma nova, assim como mostramos na live de lançamento, basta fazer EHorseException.New.Unit().Title().etc...
