### ISSUE TITLE
Maximum number of concurrent connections exceeded. Aleatoriamente

### ISSUE THREAD

**Issue by gleikocarmelo** [HashLoad/horse#245]
Estou com um problema no meu servidor Horse, onde aleatoriamente recebo a mensagem Maximum number of concurrent connections exceeded. Please try again later.
Normalmente ocorrem duas situações:
1ª A aplicação Servidor continua funcionando e recebo a referida mensagem.
2ª A aplicação Servidor trava totalmente, o consumo de processador da aplicação fica alto e tenho q forçar o encerramento da aplicação.

Já fiz diversos testes com o Postman com mais de 200 requisições de uma vez e não trava. Mas aleatoriamente ocorre uma das duas situações.

**Comment by viniciussanchez** [comment]
Você configurou o número máximo de conexões permitidas?

**Comment by gleikocarmelo** [comment]
Não, não encontrei nenhum artigo ou vídeo orientando como configurar.

**Comment by viniciussanchez** [comment]
ok, coloque aqui se resolveu depois

**Comment by viniciussanchez** [comment]
Podemos fechar essa Issue?
