### ISSUE TITLE
Erro compilação delphi XE8

### ISSUE THREAD

**Issue by ronaldobim** [HashLoad/horse#264]
Boa noite pessoal, na última versão da branch master não estou conseguindo compilar o Horse, não sei se falta algum commit na classe TMimeTypes ou alguma incompatibilidade com a minha versão do Delphi. Não está encontrando TMimeTypes.TKind. Segue imagem com o erro de compilação.

![image](https://user-images.githubusercontent.com/48992838/166338893-45f70951-086b-4e33-babe-4301df5f1e7f.png)

![image](https://user-images.githubusercontent.com/48992838/166338935-56799af5-91f5-45f7-aaf8-25065988bbe6.png)

**Comment by francomao** [comment]
Percebi esse problema também, tive que comentar a função SendFile pra compilar meu projeto.

**Comment by francomao** [comment]
Estou tentando verificar como ajudar na solução.

**Comment by gabrielbaltazar** [comment]
Bom dia pessoal.
Já está sendo resolvido e deve ser colocado na branch master ainda essa semana.

Obrigado pelo report

**Comment by francomao** [comment]
Valeu!
