### ISSUE TITLE
SSL

### ISSUE THREAD

**Issue by fernando-garoso** [HashLoad/horse#27]
Como utilizar Horse com SSL?

**Comment by viniciussanchez** [comment]
Olá, o Horse ele é apenas um serviço rodando em uma porta... o certificado, voce teria que configurar no teu servidor de aplicação, como por exemplo no IIS.

**Comment by fernando-garoso** [comment]
Opa, valeu! Se algum dia sobrar um tempinho para gerar um vídeo, seria bem legal! Muito obrigado pelo retorno!!  Enviado do Email para Windows 10 De: Vinicius SanchezEnviado:segunda-feira, 20 de abril de 2020 17:04Para: HashLoad/horseCc:fernando-garoso; AuthorAssunto: Re: [HashLoad/horse] SSL (#27) Olá, o Horse ele é apenas um serviço rodando em uma porta... o certificado, voce teria que configurar no teu servidor de aplicação, como por exemplo no IIS.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by viniciussanchez** [comment]
Pode deixar ;)
