### ISSUE TITLE
Retorno JSON

### ISSUE THREAD

**Issue by alissonrodrigo** [HashLoad/horse#277]
Bom dia,  tenho uma tabela que retorna um unico registro json 
"Res.Send<TJSONArray>(Qry.ToJSONArray());"
[
	{
		"idusuario": 2,
		"ativo": "Sim",
		"nome": "Alisson Rodrigo",
	}
]

Teria como colocar ela para em vez de retornar um array retornar apenas um json simples
{
	"idusuario": 2,
	"ativo": "Sim",
	"nome": "Alisson Rodrigo",
}
Grato

**Comment by gabrielbaltazar** [comment]
Tente usar Res.Send(Qry.ToJSONObject())

**Comment by alissonrodrigo** [comment]
> Tente usar Res.Send(Qry.ToJSONObject())

Obrigado, funcionou certinho.
