### ISSUE TITLE
'Imprimir' Rotas registradas

### ISSUE THREAD

**Issue by alissonrodrigo** [HashLoad/horse#279]
Eu consigo fazer um loop no array de todas as rotas já registradas? Assim consigo gerar a documentação da api mais rapido

**Comment by viniciussanchez** [comment]
Olha o middleware de Swagger. Ele faz a documentação das API.

**Comment by alissonrodrigo** [comment]
Sim eu vi o middleware muito bom até mesmo fiz uns testes! Porem gostaria de saber se tem como eu ter acesso a lista de rotas de todo o sistema?

**Comment by viniciussanchez** [comment]
Não lembro se o THorse.Routes te da o acesso.. mas acho que nao, precisava testar

**Comment by alissonrodrigo** [comment]
Ha sim, qualquer coisa se lembrar me confirme! Obrigado
