### ISSUE TITLE
MaxConnections fixo em 32

### ISSUE THREAD

**Issue by robson-oliveira** [HashLoad/horse#28]
Verifiquei o problema no Delphi Rio 10.3, após a quantidade de conexões chegar a 32 o retorno passa a ser [Maximum number of concurrent connections exceeded.  Please try again later], independente da definição da propriedade MaxConnections do Horse.

Foi resolvido inserindo o seguinte código na linha 82 de Horse.pas:
if FMaxConnections > 0 then
  WebRequestHandler.MaxConnections := FMaxConnections;

**Comment by viniciussanchez** [comment]
Olá, Consegue mandar um PR pra nós?

**Comment by robson-oliveira** [comment]
é que não uso o git

**Comment by viniciussanchez** [comment]
Tranquilo então... obrigado ;)

**Comment by viniciussanchez** [comment]
Atualmente o código se encontra assim:

![image](https://user-images.githubusercontent.com/16382981/80144302-a2b26900-8584-11ea-8edc-1f257d2dcc8e.png)

**Comment by robson-oliveira** [comment]
horse 1.7.1

**Comment by viniciussanchez** [comment]
Liberado a versão 1.7.2 com o ajuste.
Obrigado...

**Comment by trainneEg7** [comment]
Tambem estou com o msm problema

**Comment by viniciussanchez** [comment]
@trainneEg7 como você está com o mesmo problema? O problema já foi corrigido... qual versão do Horse você está usando?

**Comment by SergioMissias** [comment]
Boa noite! Estou tendo o mesmo problema hoje, o servidor esta respondendo com :"Maximum number of concurrent connections exceeded. Please try again later". O que pode ser? desde ja agradeço qualquer ajuda!! Obrigado!!!

**Comment by trainneEg7** [comment]
Olá, bom dia !!

Parece que ja vi algo assim, no horse é possivel definir quantas conexões
podem ter na vida do servidor, por default deve ser 10 não lembro..
Para corrigir isso coloque esse trecho de codigo antes de definir Listen do
servidor;

  THorse.MaxConnections := 15000;

em 1500 vc pode por o valor que achar melhor...


exemplo:

  THorse.MaxConnections := 15000;

   THorse.Listen(port,
      procedure
      begin
         Writeln(Format('Server is runing on %d', [tHorse.port]));
         Readln;
      end);

att.

SergioMissias ***@***.***> escreveu no dia sexta, 18/08/2023
à(s) 19:45:

**Comment by SergioMissias** [comment]
Boa tarde! Muito obrigado!!! Deu certo !!! Valeu!!!

**Comment by trainneEg7** [comment]
Boa tarde !

Otimo !

SergioMissias ***@***.***> escreveu no dia terça, 22/08/2023
à(s) 16:50:
