### ISSUE TITLE
'Web.WebBroker' cannot be put into a package

### ISSUE THREAD

**Issue by TeoWin** [HashLoad/horse#284]
[dcc32 Error] E2223 $DENYPACKAGEUNIT 'Web.WebBroker' cannot be put into a package

Delphi 11.1 professional (no webbroker in Professional?)
I have tried both the master commit and the latest release.

**Comment by viniciussanchez** [comment]
This package must not be compiled/installed. It's just to help us with development.
To install follow the installation steps in the documentation...

**Comment by TeoWin** [comment]
Sorry.. But these packages are in your releases. Normally in a componenten/source release a package is to install components in the IDE or have a runtime package. You can't expect that if you distrubute packages with source files that the regular Delphi guy is not going to install them. That is normal procedure..
