### ISSUE TITLE
Erro "Back-off restarting failed" executando no Kubernetes

### ISSUE THREAD

**Issue by rogeriorocha** [HashLoad/horse#29]
Erro "Back-off restarting failed" quando executando no kubernetes.
Conteiner não fica em pé...
possível "Exit code 0".

Obs: No docker sozinho roda normal.

att

**Comment by CarlosHe** [comment]
You can send an example?

**Comment by CarlosHe** [comment]
Can you send an example?

**Comment by CarlosHe** [comment]
You need to enable TTY

**Comment by rogeriorocha** [comment]
Work enable tty
