### ISSUE TITLE
Correção do erro JWT 2.0.10 com Lazarus

### ISSUE THREAD

**Issue by rgoncalvesrr** [HashLoad/horse#290]
Boa tarde, estou tentando implementar o Horse no Lazarus, o modulo JWT, tá apresentando o erro: 

![photo_2022-07-26_12-23-56](https://user-images.githubusercontent.com/48299846/181046260-c25a861b-6570-4a78-afad-6c6f4c8977e1.jpg)

Aqui está a solução eu apliquei na minha versão:

![photo_2022-07-26_12-23-01](https://user-images.githubusercontent.com/48299846/181046422-c228d7de-fdd9-4d4e-9698-abc26ed63041.jpg)

Se puderem aplicar a correção nos fontes eu agradeço.

Estou usando o Horse versão 3.0.2 e o JWT 2.0.10

**Comment by viniciussanchez** [comment]
Ajustado... 
https://github.com/HashLoad/horse-jwt/releases/tag/2.0.11
