### ISSUE TITLE
Apagar arquivo após o método Download

### ISSUE THREAD

**Issue by fernando-garoso** [HashLoad/horse#291]
Qual seria a melhor forma de excluir o arquivo após usar o .Download( 'nome_do_arquivo' ) ?

fiz o seguinte teste em um GET:

  Arq := TStringList.Create;
  Arq.Text := DateTimeToStr( Now() );
  Arq.SaveToFile( 'c:\temp\download-texte.txt' );
  Arq.Free;

  Res.SendFile( 'c:\temp\download-texte.txt' );

  while not DeleteFile( 'c:\temp\download-texte.txt' ) do
  begin
  end;

Mas o arquivo fica preso

**Comment by fernando-garoso** [comment]
Fiz o teste com .SendFile e Download também

**Comment by viniciussanchez** [comment]
Você poderia modificar um middleware pra voce que apos o envio ele mesmo apagasse

**Comment by fernando-garoso** [comment]
Olá Vinícius, e se nestes métodos novos existisse um parâmetro para excluir após envio ( .SendFile, .Download, ...), creio que muita gente utilizaria pois enviam arquivos de relatório, pdf, etc, somente temporário.

Valeu pelo retorno.

**Comment by viniciussanchez** [comment]
Podemos pensar nisso, se quiser mandar um pull request, podemos avaliar sim

**Comment by fernando-garoso** [comment]
Valeu!
