### ISSUE TITLE
bad benchmark test using wrk

### ISSUE THREAD

**Issue by ibelarouci** [HashLoad/horse#292]
$ wrk -t20 -c400 -d30s http://localhost:9000
Running 30s test @ http://localhost:9000
  20 threads and 400 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    14.38ms   86.98ms   1.75s    96.91%
    Req/Sec   413.86    284.05     2.73k    73.52%
  232737 requests in 30.09s, 21.31MB read
  Socket errors: connect 0, read 232731, write 0, timeout 10
Requests/sec:   7733.62
Transfer/sec:    725.05KB
#### this is benchmark test using wrk in http server created by HORSE.
you can take a look at mormot , Brook results here https://github.com/ibelarouci/nodpyvsfpcserver
what do you suggest to improve that?

**Comment by viniciussanchez** [comment]
Show me your test code please

**Comment by ibelarouci** [comment]
program Console;

{$MODE DELPHI}{$H+}

uses
  {$IFDEF UNIX}{$IFDEF UseCThreads}
  cthreads,
  {$ENDIF}{$ENDIF}
  Horse;

procedure GetPing(Req: THorseRequest; Res: THorseResponse; Next: TNextProc);
begin
  Res.Send('<h1> pong </h1>');
end;

begin
  THorse.Get('/', GetPing);
  THorse.Listen(9000);
end.

**Comment by viniciussanchez** [comment]
We will try to optimize the framework more in the next versions. Thanks.
