### ISSUE TITLE
Server em Linux com várias requisições ao mesmo tempo;

### ISSUE THREAD

**Issue by maiquelparisotto** [HashLoad/horse#296]
Boa tarde;
Estou realizando alguns testes com Horse, rodando em Linux.
No meu caso estou tendo várias requisições simultâneas, e estou recebendo erro nestas situações.

Algo que preciso configurar, ou tratar?

Meu projeto principal ficou assim:

```
TControllerSend.Registry;
TControllerCancel.Registry;
TcontrollerSearch.Registry;
THorse.Listen(9000);
```

```
class procedure TControllerSend.Registry;
begin
  THorse.Post('/send',send);
end;
```

**Comment by dliocode** [comment]
Adiciona essas configurações antes de fazer o `THorse.Listen(9000)`

```  
THorse.MaxConnections := 10000;
THorse.ListenQueue := 300;
```

**Comment by dliocode** [comment]
Para capturar qualquer Header, basta fazer isso:
`Req.Headers['MEU HEADER']`

**Comment by dliocode** [comment]
Depois verifica todas as opções presentes no `Req`
Lembra de uma coisa..

Se for para alterar algo para o usuario, a funcionalidade estará no parametro `Res`.
Se for para capturar algo da requisição que o servidor recebeu, a funcionalidade estará no parametro `Req`.

Se você quiser alterar ou adicionar algum Header para o usuario final, você vai usar o `Res.AddHeader()`

**Comment by maiquelparisotto** [comment]
Funcionou corretamente, obrigado pessoal.
Sobre o retorno, eu preciso enviar para outro endpoint, que não é o mesmo da requisição do POST..  

Tentei assim:
res.RedirectTo('endpoint');

Porém não esta trazendo o Json de resposta.

**Comment by dliocode** [comment]
@maiquelparisotto conseguiu resolver todas as questões?

**Comment by maiquelparisotto** [comment]
Sim.
Consegui criar o server em tempo de execução, respondendo de forma privada a cada requisição.
Nos testes que fizemos com requisições simultâneas, respondeu corretamente a cada solicitação.
