### ISSUE TITLE
Problemas com Horse em modo debug no lazarus

### ISSUE THREAD

**Issue by leoburn5** [HashLoad/horse#304]
Saudações:

O Lazarus oferece uma opção de auto criação de "templates" de build para o projeto, conforme temos no Delphi.

Nas opções do projeto, ao clicar no botão [...] destacado na imagem abaixo, sobe uma mensagem para criar as opções de build "Debug" e "Release" automaticamente.

![Figura 1](https://user-images.githubusercontent.com/63558173/187671195-47478ecf-9761-4287-8ea1-ea463732fba2.png)

Depois de criar os 2 modos de build, se o modo "Debug" estiver selecionado, o projeto sempre sobe uma exeption RunError(219) "Invalid Type Cast" 

![Figura 2](https://user-images.githubusercontent.com/63558173/187671298-7d7ac269-1620-4533-9621-7025c54d8368.png)

 ao chegar na linha 79 da unit "Horse.Core.RouterTree.NextCaller": 

![Figura 3](https://user-images.githubusercontent.com/63558173/187671345-6444771f-d8a3-4038-8e59-a4fe3124b1b3.png)

O projeto utilizado para isolar o problema é uma aplicação console simples contendo o exemplo oficial de aplicação console para o Lazarus:

![Figura 4](https://user-images.githubusercontent.com/63558173/187671381-4b2b53c0-6f5c-42c3-afc2-765ade75bc68.png)

Ao selecionar a opção de build "Release" o problema não ocorre.

Estou anexando o projeto zipado para referência, pois não consegui identificar a causa do problema:

Lazarus 2.2.2 com FPC 3.2.2 no Windows 11.

Horse 3.0.2.

[BackEnd.zip](https://github.com/HashLoad/horse/files/9461213/BackEnd.zip)

**Comment by andre-djsystem** [comment]
Desmarque essa opção:

![image](https://user-images.githubusercontent.com/49646398/187676791-34f4148c-50c1-4c89-a293-a8defa19bdd5.png)

**Comment by leoburn5** [comment]
Funcionou!!!

Obrigado André!
