### ISSUE TITLE
middlewares

### ISSUE THREAD

**Issue by ednergassen** [HashLoad/horse#305]
Bom dia!

Estou querendo criar um middleware que será utilizado em uma rota específica. Esse middleware, será executado antes da chamada dessa rota e irá retornar informações que serão utilizadas pela mesma, sendo assim, gostaria de saber. Como eu faço para passar essas informações para o próximo nível (rota específica)?

Estava pensando em acessar a requisição e incluir no header ou no body essas informações, só não sei se seria o procedimento adequado para isso, ou se tem outra forma de eu passar um objeto na requisição, o qual eu posso pegar no próximo nível (Next).

Obs.: Não gostaria de ter que fazer esse procedimento junto dessa rota que estou fazendo. Uma das mágicas do Horse é justamente podermos criar micro-serviços que executam determinadas funcionalidades, sem precisar colocar tudo em um ponto específico.

Desde já agradeço a atenção!

**Comment by viniciussanchez** [comment]
Bom dia, você pode colocar essas informações dentro de um objeto e armazenar ele na session da req. Lembrando que essa session, ela morre junto com a request.
