### ISSUE TITLE
Middleware handle-exception

### ISSUE THREAD

**Issue by ednergassen** [HashLoad/horse#306]
Bom dia!

Estou testando o middleware handle-exception no horse. Criei um middleware para uma funcionalidade específica. Quando gero uma EHorseException no mesmo, a execução do código não é interrompida, chegando até a minha rota que eu chamei. Apenas se utilizo o EHorseCallbackInterrupted que é interrompido.

Esse comportamento é para ser dessa forma mesmo?

**Comment by ednergassen** [comment]
Certo, mas como estou gerando uma EHorseException ele não deveria de interromper a execução do código ao invés de deixar chegar a rota que eu chamei?

**Comment by viniciussanchez** [comment]
As vezes a ordem dos middlewares tambem podem influenciar. Mas tipo, o EHorseException é pra você tratar uma exceção. O EHorseCallbackInterrupted  é para interromper

**Comment by ednergassen** [comment]
Obrigado pelos retornos Vinicius.

Confesso que não entendi direito.

Me corrige se eu estiver errado. O middleware handle-exception é para ter uma padrão de retorno em formato JSON. Eu utilizo a EHorseException para tratar o meu erro e poder passar informações mais detalhadas sobre o erro gerado. Mas mesmo assim continua sendo uma exception, ou seja, deveria de interromper a execução do código e retornar o JSON com as informações.

**Comment by gabrielbaltazar** [comment]
Não deveria lançar no EHorseCallbackInterrupted porque daí não passaria pelos demais middlewares.
