### ISSUE TITLE
Compilando para Linux Erro

### ISSUE THREAD

**Issue by Leandro-L-M-Lopes** [HashLoad/horse#308]
Olá.

Compilando para Linux, esta ocorrendo um erro de variant, conforme texto a baixo.

[DCC Fatal Error] System.VarUtils.pas(1213): E2158 System.Variants unit out of date or corrupted: missing '@VarToInteger'

![image](https://user-images.githubusercontent.com/108899741/192636270-1a7b7801-404a-42b2-a044-568c05fe6213.png)

A IDE utilizada é Rad Studio 10.2
Ubuntu 16.04.7 LTS

Agradeço a atenção de quem puder dar um help.

**Comment by gabrielbaltazar** [comment]
Algum motivo pra rodar no Ubuntu 16.04? Compilo normal no 18.04. De qualquer forma vou fazer um teste no 16.04 assim que possível.

**Comment by viniciussanchez** [comment]
@gabrielbaltazar eu sei que cada versão do Delphi, limita uma versão máxima do Ubuntu. Na versão RIO 10.3, se não me engano não conseguia compilar para versões maiores que a 18.04. Talvez esse seja o problema dele...

**Comment by Leandro-L-M-Lopes** [comment]
Oi boa tarde!

Agradeço a sua atenção!

Vou formatar o PC que está instalado o Ubuntu, para fazer novos testes.

Pensando bem vou formatar os dois PCs.

Muito obrigado!

Em qua., 5 de out. de 2022 09:40, Vinicius Sanchez ***@***.***>
escreveu:

**Comment by dliocode** [comment]
@Leandro-L-M-Lopes consegiu resolver?

**Comment by Leandro-L-M-Lopes** [comment]
Oi bom dia!

Não consegui resolver!

Formatei minha máquina do Delphi!

Reinstalei do zero!

Aí funcionou!

Compilou para o Ubuntu!

Coloquei para rodar Ubuntu Server, junto com o banco de dados Firebird 3.0,
funcionou muito bom!

A máquina que eu trabalho veio de outro usuário, poderia estar com alguma
alteração na instalação do Delphi, que impedia a compilação para Linux.

Muito top Horse!
Gostei muito de mexer com ele!

Obrigado pela atenção!



Em seg., 12 de dez. de 2022 13:55, Danilo Lucas ***@***.***>
escreveu:

**Comment by dliocode** [comment]
@Leandro-L-M-Lopes showw..
