### ISSUE TITLE
Função Download com nome de saída do arquivo diferente

### ISSUE THREAD

**Issue by fcmatos** [HashLoad/horse#313]
Seria possível ter uma opção de donwload com o nome de saída do arquivo diferente?
Exemplo: Res.Download('E:\temp\foto.jpg','arquivo.jpg');

**Comment by viniciussanchez** [comment]
Não da pra fazer por exemplo com o SendFile()?

**Comment by viniciussanchez** [comment]
Se não for pedir muito, o que acha de enviar um Pull Request para o projeto? Assim seu nome aparece como contribuidor.
