### ISSUE TITLE
Upload de arquivos

### ISSUE THREAD

**Issue by alissonrodrigo** [HashLoad/horse#316]
Bom dia, eu tinha visto algo sobre upload de arquivos via stream "Req.ContentFields" mas não conseguir achar a documentação ou exemplo sobre seu uso.
Gostaria de poder enviar vários arquivos ao servidor horse e serar o nome e tipo do arquivo na hora do envio tem como?

**Comment by antoniojmsjr** [comment]
Blz, a opção de envio de múltiplos arquivos se chama **multipart/form-data** e tu pode usar o framework [RESTRequest4Delphi](https://github.com/viniciussanchez/RESTRequest4Delphi) usando as funções:

- AddField
- AddFile

Exemplo de uso: 

https://user-images.githubusercontent.com/20980984/187557326-1b25cc60-275d-4048-a06b-7366d4884c0a.mp4

Fonte do exemplo: https://github.com/viniciussanchez/RESTRequest4Delphi/tree/master/samples

- [Client](https://github.com/viniciussanchez/RESTRequest4Delphi/tree/master/samples/client)
- [server-horse](https://github.com/viniciussanchez/RESTRequest4Delphi/tree/master/samples/server-horse)

**Comment by viniciussanchez** [comment]
Bom dia, como @antoniojmsjr disse, upload de arquivos teria que ser feito usando outra ferramenta, como por exemplo, o RR4D que ele colocou. Porque o Horse é apenas para API, ele vai receber os arquivos enviados. E ai você pode pegar os arquivos usando o "Req.ContentFields" que você citou. Mas para enviar os arquivos, teria que usar o RR4D porque é o client enviando arquivos para o server. E o Horse atua apenas no lado do servidor.

**Comment by alissonrodrigo** [comment]
Do lado cliente trabalho com RR4D que faz o envio do arquivo com o comando

      Response := TRequest.New.BaseURL(Servidor).Resource(sURL).AddFile('stream', aStream).Post;

e do lado servidor trato da sequinte maneira

procedure UploadFoto(Req: THorseRequest; Res: THorseResponse; Next: TProc);
var
  Pessoas: TdmPessoas;
  LStream: TMemoryStream;
  sCPF: string;
  sPath, sArquivo, sPathArquivo: string;
  Qry: TFDQuery;
begin
  Pessoas := TdmPessoas.Create(nil);
  sCPF := Req.Params['cpf'];
  sArquivo := FormatDateTime('yymddhhnnsszzz', Now) + '.webp';
  sPath := TConfigIni.LerValor('ARQUIVOS', 'PATH');
  sPathArquivo := sPath + '\' + sArquivo;

  if Req.ContentFields.Field('stream').AsStream <> nil then
  begin
    LStream := TMemoryStream.Create;
    try
      LStream.LoadFromStream(Req.ContentFields.Field('stream').AsStream);
      LStream.SaveToFile(sPathArquivo);
      Pessoas.Update_PathFoto(sCPF, sArquivo);
    finally
      LStream.Free;
      Pessoas.Free;
    end;

  end;

  Res.Send('{"status":"salvo"}').Status(201);

end;

eu vi um exemplo aqui tratando vários arquivos e também passando o nome e extensão do arquivo mas não encontro mais.
poderiam me ajudar?

**Comment by antoniojmsjr** [comment]
No exemplo que te falei no lado do servidor [server-horse](https://github.com/viniciussanchez/RESTRequest4Delphi/tree/master/samples/server-horse) tem o que você precisa.

```delphi
//file
  for I := 0 to Pred(pReq.RawWebRequest.Files.Count) do
  begin
    if (pReq.RawWebRequest.Files.Items[I].FieldName = 'file') then
    begin
      lFile := TMemoryStream.Create;
      try
        lFile.LoadFromStream(pReq.RawWebRequest.Files.Items[I].Stream);
        lFile.Position := 0;
        lFile.SaveToFile(ExtractFilePath(ParamStr(0)) + pReq.RawWebRequest.Files.Items[I].FileName);
        lblMultipartFormDataFile.Caption := Format('%s%s', [ExtractFilePath(ParamStr(0)), pReq.RawWebRequest.Files.Items[I].FileName]);
      finally
        lFile.Free;
      end;
    end;
  end;
```
