### ISSUE TITLE
can i delete some property from http header?

### ISSUE THREAD

**Issue by kabiri** [HashLoad/horse#324]
how to delete some property from http header?
for example : 
Access-Control-Allow-Origin
Access-Control-Allow-Credentials
Connection
...

**Comment by kabiri** [comment]
I have a ready client that doesn't care about the server's response when there is a property in the html header that it doesn't expect, so I have to remove some of the header properties.
But I don't know how.

**Comment by viniciussanchez** [comment]
Thanks for the contribution...
In the next version:
![image](https://user-images.githubusercontent.com/16382981/218802337-ea69aa3f-9b81-4af5-80d7-6bdf20f31f16.png)
