### ISSUE TITLE
Errro compilação

### ISSUE THREAD

**Issue by wiltonlp** [HashLoad/horse#326]
Bom dia!

Não consigo compilar a nova versão, ocorre o seguinte erro nas linhas 1, 2, 3 e 4 do exemplo: [dcc32 Error] Main.Form.pas(83): E2064 Left side cannot be assigned to

Usei o exemplo VCL_SSL, disponivel na pasta: samples\delphi\vcl-ssl. 

  with THorse.IOHandleSSL do
  begin
   Linha 1 - KeyFile := leKey.Text;
   Linha 2 - CertFile := leCrt.Text;
   Linha 3 - SSLVersions := [sslvTLSv1_2];
   Linha 4 - Active := True;
  end;

**Comment by viniciussanchez** [comment]
Bom dia, você baixou o código direto provavelmente
Ou baixou a release? Aconselho sempre usar a última release liberada:
![image](https://user-images.githubusercontent.com/16382981/211578108-8d3ebf10-52ae-4a2c-b886-78dca5c6bb1d.png)
https://github.com/HashLoad/horse/archive/refs/tags/3.0.2.zip
Ou usar o boss para efetuar a instalação

**Comment by wiltonlp** [comment]
Não baixei a release, na realidade estava testando/verificando se as versões/fontes mais recentes resolvem o problema de codificação que estou enfrentando. Os erros/mensagens retornados para aplicação, estão com formato ilegível em caso de acentuações. 

No exemplo raise exception.Create('Não é permitido'), o resultato é: N\u00E3o \u00E9 permitido. Tem alguma dica para resolver o problema de codificação?

**Comment by viniciussanchez** [comment]
Isso é encode... não tem a ver com os códigos do horse.

**Comment by wiltonlp** [comment]
Resolvido.  Obrigado!
