### ISSUE TITLE
Erro acentuação com uso do Middleware Compression

### ISSUE THREAD

**Issue by RichIgor** [HashLoad/horse#334]
Olá equipe Hashload, deparei com o seguinte problema e após alguns testes descobri que a causa é quando uso o middleware Compression.

Fiz um pequeno exemplo para ilustrar o problema:

```
THorse.Get('/ping',
    procedure(Req: THorseRequest; Res: THorseResponse; Next: TProc)
    begin
      Res.Send('éçã');
    end);
```

**Sem uso do Compression - Resultado Correto**
```
THorse
     .Use(CORS)
     .Use(HorseJWT(chaveHorse, THorseJWTConfig.New.SkipRoutes(['/login'])))
     //.Use(Compression(1))
     .Use(Jhonson())
     .Use(HandleException);
```
![image](https://user-images.githubusercontent.com/70984325/227933459-86281feb-be09-460d-a30d-404f98980cd1.png)

**Com uso do Compression - Falha**
```
THorse
     .Use(CORS)
     .Use(HorseJWT(chaveHorse, THorseJWTConfig.New.SkipRoutes(['/login'])))
     .Use(Compression(1))
     .Use(Jhonson())
     .Use(HandleException);
```
![image](https://user-images.githubusercontent.com/70984325/227933317-2e7bc6b4-1f80-4a61-94f1-6686ad029069.png)

**Comment by dliocode** [comment]
Abra uma ISSUES no [https://github.com/HashLoad/horse-compression](https://github.com/HashLoad/horse-compression)

**Comment by dliocode** [comment]
@RichIgor, fiz o ajuste [Horse-Compression - #13](https://github.com/HashLoad/horse-compression/pull/13)

**Comment by RichIgor** [comment]
Obrigado @dliocode!

Perdão por não abrir a issue no https://github.com/HashLoad/horse-compression, vou manter aqui a resposta apenas para não duplicar!

Quando o retorno é json esta realmente resolvido, entretanto em retorno text ocorre o mesmo problema!

Abraços!

**Comment by dliocode** [comment]
O ajuste que eu fiz ali, vai resolver.. Qualquer coisa só avisar, vou fechar a issue!
