### ISSUE TITLE
How to replace TIdHTTPWebBrokerBridge with mormot？

### ISSUE THREAD

**Issue by Yang-Ya-Chao** [HashLoad/horse#336]

**Comment by viniciussanchez** [comment]
I didn't understand.

**Comment by Yang-Ya-Chao** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Yang-Ya-Chao** [comment]
What I mean is that the TIdHTTPWebBrokerBridge used at the bottom of Horse comes from Indy. Can we replace it with http.sys, just like in Mormot

**Comment by Yang-Ya-Chao** [comment]
I tried using someone else's code to replace it, but he has a problem now, it's not perfect and needs help。
from ：https://www.cnblogs.com/Yang-YaChao/p/17269989.html

**Comment by Yang-Ya-Chao** [comment]
Replacing http.sys works, but it's not perfect

**Comment by Yang-Ya-Chao** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by viniciussanchez** [comment]
Hello @Yang-Ya-Chao, if you can make the provider, please send us a Pull request.

**Comment by Yang-Ya-Chao** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Yang-Ya-Chao** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
