### ISSUE TITLE
Erro ao compilar projeto na nova versão do horse.

### ISSUE THREAD

**Issue by aesjunior2707** [HashLoad/horse#337]
Pessoal estou trabalhando em um projeto novo e atualizei meu horse para versão mais recente (3.1.0) , hoje trabalho com o delphi seattle e apareceu esse erro ao compilar o projeto. 

![image](https://user-images.githubusercontent.com/54411625/228850464-c4d6c247-0735-4937-a6df-9c0e6c28f140.png)

**Comment by dliocode** [comment]
Faça essa alteração:  [#333](https://github.com/HashLoad/horse/pull/333/files)

**Comment by viniciussanchez** [comment]
Pode atualizar também para a versão 3.1.1 que estará resolvido esse problema de compatibilidade com versões antigas do Delphi
