### ISSUE TITLE
Erro ao atualizar a versão

### ISSUE THREAD

**Issue by vipeol** [HashLoad/horse#350]
### Discussed in https://github.com/HashLoad/horse/discussions/349

<div type='discussions-op-text'>

<sup>Originally posted by **vipeol** June 21, 2023</sup>
Olá,

 Ao executar o comando boss update, e atualizar os fontes do projeto, ao tentar compilar esta dando o seguinte erro no arquivo

[dcc32 Error] Horse.ServerStatic.pas(50): E2003 Undeclared identifier: 'TKind'   e logo abaixo outro erro
[dcc32 Error] Horse.ServerStatic.pas(103): E2003 Undeclared identifier: 'Default'

</div>

**Comment by viniciussanchez** [comment]
Como respondido na discussão, isso não é erro do Horse e sim de algum middleware que está utilizando. Verifique no middleware em questão, e abra uma issue lá... para que o criado possa dar uma olhada e resolver o problema
