### ISSUE TITLE
[Dúvida] - Horse callback

### ISSUE THREAD

**Issue by LukeChagastec** [HashLoad/horse#354]
Boa tarde.

Ao desenvolver minha API com o Horse, me deparei com uma situação no _curiosa_.

Tanto no delphi, quanto no lazarus, podemos implementar métodos (procedures ou funções) que podem ser ou não ligadas à uma classe.

No meu caso, ao implementar uma chamada get/post, me deparei com a situação, onde todos os callbacks previstos na api não são integrados a uma classe, mas sim métodos "soltos".

![image](https://github.com/HashLoad/horse/assets/89275370/405e8f3e-38e7-43aa-ba6f-d891eb737677)

Seria possível implementar um THorseCallback, ligado a um objeto, utilizando procedure of object em vez de diretamente procedures?

**Comment by viniciussanchez** [comment]
sim, poderia trabalhar com classes, assim como os eventos dos botões por exemplos
