### ISSUE TITLE
Erro de compilação com Lazarus 3.0, FPC 3.2.2, Ubuntu 23.10 e Horse Trunk

### ISSUE THREAD

**Issue by edsontmarques** [HashLoad/horse#359]
No meu projeto eu criei os build modes Debug e Release.
No build mode Debug temos as seguintes diretivas de compilação:

-dEnableMultithreading
-dUseCThreads
-FcUTF8
-dDebuging
-dHORSE_FPC_FUNCTIONREFERENCES

E no Release temos:

-dEnableMultithreading
-dUseCThreads
-FcUTF8
-dHORSE_FCGI
-dHORSE_FPC_FUNCTIONREFERENCES

Quando compilo com Release não ocorre o erro.

Quando compilo com Debug ocorre o erro de compilação na linha 480 da unit Horse.core:

`THorseCallback(ACallbackRequest);`

Por aqui eu acrescentei "()" e ficou assim:

` THorseCallback(ACallbackRequest());`

Fiz o mesmo procedimento também na linha 452 desta mesma unit.
Isso permitiu que a compilação fosse executada finalizada.

**Comment by viniciussanchez** [comment]
Bom dia... acabei de baixar a última versão do Lazarus disponível para download.

![image](https://github.com/HashLoad/horse/assets/16382981/a73b9152-b829-47e1-9c3e-20482b7646ad)

Ao realizar o teste, o projeto para de compilar como mostra a imagem abaixo.

![image](https://github.com/HashLoad/horse/assets/16382981/fa522e12-6e34-40ed-8d19-cbbeef71eae4)

Teria alguma forma de usar alguma diretiva de compilação para só aplicar essa alteração quando for a versão que você está utilizando ou algo assim?

**Comment by edsontmarques** [comment]
Boa tarde!
Rapaz ... que situação curiosa ! 
Eu tive que fazer alguns ajustes aqui no meu projeto por causa de uns problemas com o uso da heaptrc (no projeto para Linux).
Com isso eu removi da diretiva -dDebuging que eu mesmo acrescentei no Project Options (Build Mode Debug) pois ela acabou não sendo mais necessária. 
Paralelamente a isso eu resolvi fazer uma nova merge local do repositório origin/master do horse... e com isso o código da unidade Horse.Core voltou ao original removendo o "()" que eu havia acrescentado localmente aqui, nas linhas 452 e 480.
Depois disso eu estive fazendo uns testes com a implementação básica de exemplo do horse e percebi que o exemplo da página do horse estava compilando normalmente aqui no meu ambiente.
Então, agora há pouco, eu voltei novamente ao meu projeto e consegui compilar e rodá-lo sem problemas também. Com isso agora não sei o que pode ter causado o problema que eu estava observando anteriormente.

Vou fechar esta issue.
Desde já agradeço.
