### ISSUE TITLE
Delphi 11 + Horse + ReactJs + Axios

### ISSUE THREAD

**Issue by ageu** [HashLoad/horse#380]
Estou com um erro no Projeto com Horse
Mensagem: 
Project prjAreaAlunoWinAPI.exe raised exception class EHorseCallbackInterrupted with message ''.

Eu já percebi que, quando se usa o ReactJS com axios, é feito 2 requisições, uma usando o método POST e outra usando o OPTIONS.
Pelo Postman executa normal se erros.
Como resolver ou contornar isso?

**Comment by 1Dragon** [comment]
Está usando o midleware cors?

ageu ***@***.***> escreveu em qua., 13/03/2024 às 02:15 :

**Comment by viniciussanchez** [comment]
Toda aplicação JS faz duas requisições, uma com o verbo HTTP OPTIONS para validar o CORS. Você deve primeiramente usar o middleware de CORS. No caso imagino que já esteja usando pela mensagem que apresentou. Essa mensagem é normal em modo debug, visto que a requisição para validação do CORS, não precisa ser executada por completo, sendo assim, o próprio middleware lança uma exceção interna (controlada) para encerrar a requisição assim que validado o CORS.
Caso você não entenda muito sobre CORS, aconselho fortemente a dar uma estudada, é muito importante em mundos web, envolvendo aplicações JS.

**Comment by ageu** [comment]
> vendo aplicações JS

sim, estou utilizando o midleware CORS no Horse.
Então esta excessão que gera é somente em DEBUG, na aplicação rodando não vai dar problema?

**Comment by viniciussanchez** [comment]
Não...
