### ISSUE TITLE
Ao realizar mais de 50 requisições ao mesmo tempo, esta gerando o erro: i/O error 103

### ISSUE THREAD

**Issue by AlephMeloSG** [HashLoad/horse#383]
Criando uma api simples contendo Cors, jhonson e horseswagger, ao criar uma requisição qualquer que returna uma string por exemplo, caso seja realizado mais de 50 requisições em menos de 1 segundo, algumas requisições estão falhando antes de entrar na função criada para a requisição

**Comment by viniciussanchez** [comment]
Sobe um exemplo para que possa ser analisado
