### ISSUE TITLE
Isso já foi ajustado pelo Alexandre Magno, mas ainda não subimos a alteração. Em breve esse problema de congelamento estará resolvido

### ISSUE THREAD

**Issue by RobertoSobreira01** [HashLoad/horse#395]
Isso já foi ajustado pelo Alexandre Magno, mas ainda não subimos a alteração. Em breve esse problema de congelamento estará resolvido

_Originally posted by @viniciussanchez in https://github.com/HashLoad/horse/discussions/153#discussioncomment-3692303_

no ambiente lazarus v3.4 - x86_64-linux-gtk2 - e horse 3.1.6 - tra travando nesse ponto..

**Comment by viniciussanchez** [comment]
Comitei as alterações do magno. Em breve vamos liberar uma versão release.
