### ISSUE TITLE
erro ao usar o Basic Authenticator

### ISSUE THREAD

**Issue by SergioMissias** [HashLoad/horse#398]
Boa tarde!
Ao tentar compilar o servidor com o BAsic authenticator está dando erro na Procedure MidlleWARE 
na linha
  if MatchRoute(LPathInfo, Config.SkipRoutes) then

a funcao  MatchRoute  não encontrada, e não acho alguma unit com essa funcao

o que pode ser?

Obrigado

**Comment by jcaique** [comment]
![image](https://github.com/user-attachments/assets/d7565ad2-6ca5-4cad-bec6-e5efa61befef)
Não estaria nesta unit?

**Comment by viniciussanchez** [comment]
Provavelmente está com algum projeto desatualizado.. confira ai por favor
