### ISSUE TITLE
Thread

### ISSUE THREAD

**Issue by WhebertonFialho** [HashLoad/horse#408]
Como consigo Starta o serviço do horse em um tread separada?
Ele abre e fecha logo em seguida.

**Comment by viniciussanchez** [comment]
Mas qual a necessidade? Se para cada requisição, uma thread já é criada?

**Comment by WhebertonFialhoUnisystem** [comment]
Opa, era para fazer uma outra automação dentro do webservice, mas ja resolvi... vlw man
