### ISSUE TITLE
websocket support?

### ISSUE THREAD

**Issue by arvanus** [HashLoad/horse#49]
Hi, I don't use horse yet, but I had built-ed a websocket client for Delphi (and probably pascal too) 
Does horse has websocket support?
If not, is there interest to add Websocket do Horse?
Thanks

**Comment by leogregianin** [comment]
Hi @arvanus, there is already a middleware for this, see [here](https://github.com/WillHubner/Horse-SocketIO).

**Comment by arvanus** [comment]
Ok, Thank you!
