### ISSUE TITLE
Implementei  compatibilidade para modulo Apache.

### ISSUE THREAD

**Issue by claudiostocco** [HashLoad/horse#60]
Implementei a compatibilidade do Horse com o Apache 2.4. Por enquanto só testei no windows, depois vou ver como fica no linux, mas funcionou legal.
Só tem que tomar cuidado com o middleware de log, lembrando que a pasta de execução do apache é a pasta bin, para salvar o log do logger tem que usar ../logs. Se ele não encontrar um caminho válido da violação de memória no Apache.

Segue o código que implementei e um exemplo. Se acharem minha contribuição interessante e puderem adicionar ao projeto.

Claudio
[Horse.Apache.zip](https://github.com/HashLoad/horse/files/5002957/Horse.Apache.zip)
[Sample.zip](https://github.com/HashLoad/horse/files/5002958/Sample.zip)

**Comment by snakeice** [comment]
Oh very good, very good!! I recommend sending a pull request with this code to stay on the list of [git contributors](https://github.com/HashLoad/horse/graphs/contributors)! 😍
